# Generated by Django 4.2.3 on 2023-07-11 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discountpercentage', models.FloatField()),
                ('Date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groceryitems', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('Discounts', models.CharField(max_length=80)),
                ('date', models.DateField()),
            ],
        ),
    ]
