# Generated by Django 4.2.3 on 2023-07-04 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Grocery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('groceryitems', models.CharField(max_length=50)),
                ('price', models.FloatField()),
                ('date', models.DateField()),
            ],
        ),
    ]
